initial commit

diff --git a/.github/workflows/deploy_green.yml b/.github/workflows/deploy_green.yml
--- a/.github/workflows/deploy_green.yml
+++ b/.github/workflows/deploy_green.yml
@@ -51,11 +51,25 @@ jobs:
 
           ssh -i private_key.pem $SSH_USERNAME@$SSH_HOST << EOF
             cd $DEPLOY_DIR
+            echo "Contents of $DEPLOY_DIR"
+            ls -al 
+            
             sudo apt update -y
             sudo apt install npm -y
             sudo npm install -g pm2 -y
-            npm install
-            pm2 start index.js --name backend-green --watch -f || pm2 restart backend-green
+            if [ -f package.json ]; then
+              npm install -y
+            else
+              echo "package.json not found!"
+              exit 1
+            fi        
+            if [ -f index.js ]; then    
+              pm2 start index.js --name backend-green --watch -f || pm2 restart backend-green
+            else
+              echo "index.js not found!"
+              exit 1
+            fi
+            pm2 save
           EOF
 
       - name: Configure Nginx for Green
